import type { College } from "@/types/college";

export const COLLEGES: College[] = [
  {
    id: "iit-bombay",
    name: "IIT Bombay",
    shortName: "IITB",
    location: "Mumbai, Maharashtra",
    state: "Maharashtra",
    type: "Government",
    streams: ["Engineering", "Technology", "Science"],
    exams: ["JEE Advanced"],
    ranking: { nirf: 3, qs: 118, times: 251 },
    rating: 4.8,
    totalRating: 2840,
    fees: { min: 200000, max: 280000, annual: 240000 },
    placement: { avg: 2100000, highest: 25000000, rate: 97, median: 1800000 },
    campusSize: "550 acres",
    established: 1958,
    accreditation: ["NBA", "NAAC A++"],
    facilities: ["Central Library", "Olympic Pool", "Research Labs", "Hostels", "Medical Center", "Innovation Cell"],
    topRecruiters: ["Google", "Microsoft", "Goldman Sachs", "McKinsey", "Amazon", "Intel"],
    image: "https://images.unsplash.com/photo-1562774053-701939374585?w=900&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=800&q=80",
      "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&q=80",
      "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&q=80",
      "https://images.unsplash.com/photo-1571260899304-425eee4c7efc?w=800&q=80",
    ],
    description:
      "Indian Institute of Technology Bombay is one of India's premier engineering institutions, consistently ranked among the top universities in Asia. Founded in 1958, IIT Bombay is known for its cutting-edge research, world-class faculty, and exceptional alumni network spanning global technology and business leaders. The institute runs over 50 academic programmes and is home to 14 departments, 16 centres of excellence, and a thriving startup ecosystem.",
    highlights: ["#3 in NIRF 2024", "550-acre Green Campus", "97% Placement Rate", "QS World Rank 118"],
    courses: [
      { name: "B.Tech Computer Science & Engineering", duration: "4 years", fees: 240000, seats: 120, cutoff: "99.9 percentile" },
      { name: "B.Tech Electrical Engineering", duration: "4 years", fees: 240000, seats: 100, cutoff: "99.8 percentile" },
      { name: "B.Tech Mechanical Engineering", duration: "4 years", fees: 240000, seats: 120, cutoff: "99.5 percentile" },
      { name: "B.Tech Chemical Engineering", duration: "4 years", fees: 240000, seats: 80, cutoff: "99.0 percentile" },
      { name: "M.Tech CSE", duration: "2 years", fees: 120000, seats: 60, cutoff: "GATE 98 percentile" },
      { name: "M.Tech AI & Data Science", duration: "2 years", fees: 120000, seats: 40, cutoff: "GATE 97 percentile" },
    ],
    reviews: [
      { author: "Rahul Mehta", batch: "2022", rating: 5, text: "Best decision of my life. World-class faculty, amazing peer group, and placements are insane. Google, Amazon, Goldman all come here. The culture of innovation is unmatched anywhere in India.", course: "B.Tech CSE" },
      { author: "Priya Krishnan", batch: "2021", rating: 5, text: "Academically rigorous but extremely rewarding. The research opportunities are unparalleled in India. Campus life is vibrant with 100+ student clubs and a strong culture of innovation.", course: "B.Tech EE" },
      { author: "Ankit Verma", batch: "2023", rating: 4, text: "Great faculty and infrastructure. The startup ecosystem here is world-class. Some departments are better than others but overall a fantastic experience.", course: "M.Tech CSE" },
    ],
    tags: ["IIT", "Top 5", "Research Hub", "Placement Powerhouse"],
    nirfCategory: "IIT",
  },
  {
    id: "iit-delhi",
    name: "IIT Delhi",
    shortName: "IITD",
    location: "New Delhi, Delhi",
    state: "Delhi",
    type: "Government",
    streams: ["Engineering", "Technology", "Science", "Management"],
    exams: ["JEE Advanced"],
    ranking: { nirf: 2, qs: 197, times: 301 },
    rating: 4.7,
    totalRating: 3120,
    fees: { min: 200000, max: 280000, annual: 250000 },
    placement: { avg: 2200000, highest: 28000000, rate: 98, median: 1900000 },
    campusSize: "320 acres",
    established: 1961,
    accreditation: ["NBA", "NAAC A++"],
    facilities: ["Central Library", "Sports Complex", "Research Labs", "Hostels", "Innovation Hub", "Bank on Campus"],
    topRecruiters: ["Google", "Microsoft", "BCG", "Qualcomm", "Samsung", "Zomato"],
    image: "https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=900&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&q=80",
      "https://images.unsplash.com/photo-1571260899304-425eee4c7efc?w=800&q=80",
      "https://images.unsplash.com/photo-1509062522246-3755977927d7?w=800&q=80",
    ],
    description:
      "IIT Delhi, established in 1961, stands as one of India's most prestigious technical institutions. Located in the heart of the national capital, it offers unparalleled access to India's top corporations, government bodies, and research organizations. Known for producing CXOs, Nobel laureates, and tech entrepreneurs, IIT Delhi's proximity to Delhi-NCR's booming startup ecosystem makes it uniquely positioned for industry collaboration.",
    highlights: ["#2 in NIRF 2024", "320-acre Urban Campus", "98% Placement Rate", "Heart of Delhi-NCR"],
    courses: [
      { name: "B.Tech Computer Science & Engineering", duration: "4 years", fees: 250000, seats: 90, cutoff: "99.9 percentile" },
      { name: "B.Tech Electronics & Communication", duration: "4 years", fees: 250000, seats: 80, cutoff: "99.8 percentile" },
      { name: "B.Tech Civil Engineering", duration: "4 years", fees: 250000, seats: 80, cutoff: "99.0 percentile" },
      { name: "B.Tech Production & Industrial", duration: "4 years", fees: 250000, seats: 60, cutoff: "98.5 percentile" },
      { name: "M.Tech VLSI Design", duration: "2 years", fees: 115000, seats: 30, cutoff: "GATE 97 percentile" },
    ],
    reviews: [
      { author: "Arjun Sharma", batch: "2023", rating: 5, text: "Capital city advantage is real. Startups, internships, government projects — all at your doorstep. Academic quality is exceptional. The alumni network in Delhi-NCR is extremely active and helpful.", course: "B.Tech CSE" },
      { author: "Sneha Gupta", batch: "2022", rating: 4, text: "Excellent faculty and superb infrastructure. The location advantage over other IITs is massive. Placements are consistently among the best in the country.", course: "B.Tech ECE" },
    ],
    tags: ["IIT", "Top 5", "Capital City", "Industry Connect"],
    nirfCategory: "IIT",
  },
  {
    id: "iit-madras",
    name: "IIT Madras",
    shortName: "IITM",
    location: "Chennai, Tamil Nadu",
    state: "Tamil Nadu",
    type: "Government",
    streams: ["Engineering", "Technology", "Science", "Management"],
    exams: ["JEE Advanced"],
    ranking: { nirf: 1, qs: 227, times: 351 },
    rating: 4.9,
    totalRating: 2960,
    fees: { min: 200000, max: 280000, annual: 245000 },
    placement: { avg: 2300000, highest: 31000000, rate: 98, median: 2000000 },
    campusSize: "620 acres",
    established: 1959,
    accreditation: ["NBA", "NAAC A++"],
    facilities: ["Research Park", "Sports Complex", "Guest House", "Hospital", "Bank", "Post Office"],
    topRecruiters: ["Google", "Apple", "Goldman Sachs", "Nvidia", "Qualcomm", "DE Shaw"],
    image: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=900&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1519452575417-564c1401ecc0?w=800&q=80",
      "https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=800&q=80",
    ],
    description:
      "IIT Madras holds the distinction of being India's #1 institute in NIRF rankings for eight consecutive years. Set in a stunning 620-acre forested campus in Chennai, IIT Madras is home to India's first Research Park — a thriving ecosystem of deep-tech startups and corporate R&D labs. The institute is renowned for its academic rigour, research output, and exceptional placement record.",
    highlights: ["#1 in NIRF 2024 (8 consecutive)", "620-acre Forest Campus", "98% Placement Rate", "India's First Research Park"],
    courses: [
      { name: "B.Tech Computer Science & Engineering", duration: "4 years", fees: 245000, seats: 80, cutoff: "99.9+ percentile" },
      { name: "B.Tech Aerospace Engineering", duration: "4 years", fees: 245000, seats: 60, cutoff: "99.7 percentile" },
      { name: "B.Tech Ocean Engineering", duration: "4 years", fees: 245000, seats: 40, cutoff: "98.5 percentile" },
      { name: "M.Tech Data Science & AI", duration: "2 years", fees: 120000, seats: 40, cutoff: "GATE 99 percentile" },
    ],
    reviews: [
      { author: "Karthik R.", batch: "2022", rating: 5, text: "India's #1 for a reason. The Research Park is something else entirely — you have Microsoft, Samsung R&D, and 300+ startups right on campus. Faculty are world-class researchers.", course: "B.Tech CSE" },
    ],
    tags: ["IIT", "#1 NIRF", "Research Park", "Top Placements"],
    nirfCategory: "IIT",
  },
  {
    id: "nit-trichy",
    name: "NIT Tiruchirappalli",
    shortName: "NIT Trichy",
    location: "Tiruchirappalli, Tamil Nadu",
    state: "Tamil Nadu",
    type: "Government",
    streams: ["Engineering", "Technology"],
    exams: ["JEE Main"],
    ranking: { nirf: 9, qs: null },
    rating: 4.5,
    totalRating: 1890,
    fees: { min: 130000, max: 180000, annual: 155000 },
    placement: { avg: 1200000, highest: 8000000, rate: 94, median: 900000 },
    campusSize: "800 acres",
    established: 1964,
    accreditation: ["NBA", "NAAC A+"],
    facilities: ["Central Library", "Sports Complex", "Research Labs", "Hostels", "Bank on Campus", "Medical Center"],
    topRecruiters: ["TCS", "Wipro", "Infosys", "L&T", "Cognizant", "Hexaware"],
    image: "https://images.unsplash.com/photo-1568792923760-d70635a89fdc?w=900&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1509062522246-3755977927d7?w=800&q=80",
      "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&q=80",
    ],
    description:
      "NIT Tiruchirappalli, consistently ranked as India's top NIT, is renowned for academic excellence, a strong alumni network, and an outstanding placement record. The sprawling 800-acre campus offers a holistic educational experience with state-of-the-art laboratories and a vibrant cultural scene. Graduates from NIT Trichy hold leadership positions across global MNCs and top Indian conglomerates.",
    highlights: ["#1 NIT in India", "800-acre Grand Campus", "94% Placement Rate", "Strong Global Alumni"],
    courses: [
      { name: "B.Tech Computer Science & Engineering", duration: "4 years", fees: 155000, seats: 60, cutoff: "98.5 percentile" },
      { name: "B.Tech Mechanical Engineering", duration: "4 years", fees: 155000, seats: 120, cutoff: "97.5 percentile" },
      { name: "B.Tech Chemical Engineering", duration: "4 years", fees: 155000, seats: 60, cutoff: "95.0 percentile" },
      { name: "B.Tech Civil Engineering", duration: "4 years", fees: 155000, seats: 80, cutoff: "94.0 percentile" },
    ],
    reviews: [
      { author: "Deepak Rajesh", batch: "2022", rating: 4, text: "Best NIT in India hands down. Placements are exceptional for a government college. Campus life and cultural fests are amazing. Faculty are experienced and industry-connected.", course: "B.Tech Mechanical" },
      { author: "Lavanya S.", batch: "2023", rating: 5, text: "Beautiful campus, incredible peer group. The infrastructure rivals private colleges. Placement season is electric — over 200 companies visit every year.", course: "B.Tech CSE" },
    ],
    tags: ["NIT", "Top NIT", "South India", "Value for Money"],
    nirfCategory: "NIT",
  },
  {
    id: "bits-pilani",
    name: "BITS Pilani",
    shortName: "BITS",
    location: "Pilani, Rajasthan",
    state: "Rajasthan",
    type: "Deemed",
    streams: ["Engineering", "Technology", "Science", "Pharmacy"],
    exams: ["BITSAT"],
    ranking: { nirf: 27, qs: null },
    rating: 4.6,
    totalRating: 2100,
    fees: { min: 450000, max: 600000, annual: 520000 },
    placement: { avg: 1800000, highest: 20000000, rate: 95, median: 1500000 },
    campusSize: "350 acres",
    established: 1964,
    accreditation: ["NAAC A"],
    facilities: ["Innovation Centre", "Multiple Libraries", "Olympic Gym", "Hostels", "Cafeterias", "Cricket Ground"],
    topRecruiters: ["Microsoft", "Google", "Schlumberger", "Goldman Sachs", "DE Shaw", "Sprinklr"],
    image: "https://images.unsplash.com/photo-1606761568499-6d2451b23c66?w=900&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&q=80",
      "https://images.unsplash.com/photo-1504275107627-0c2ba7a43dba?w=800&q=80",
    ],
    description:
      "BITS Pilani is India's most respected private engineering university, known for its unique Practice School program, highly flexible curriculum, and extraordinary startup culture. The BITS alumni network includes founders of Flipkart, Snapdeal, OYO, and hundreds of global tech companies. Students routinely bag international pre-placement offers through PS-II at top companies worldwide.",
    highlights: ["#1 Private Engineering", "Practice School Program", "95% Placement Rate", "Legendary Alumni Network"],
    courses: [
      { name: "B.E. Computer Science", duration: "4 years", fees: 520000, seats: 180, cutoff: "BITSAT 380+" },
      { name: "B.E. Electronics & Instrumentation", duration: "4 years", fees: 520000, seats: 120, cutoff: "BITSAT 360+" },
      { name: "B.E. Mechanical Engineering", duration: "4 years", fees: 500000, seats: 120, cutoff: "BITSAT 340+" },
      { name: "B.Pharm", duration: "4 years", fees: 480000, seats: 60, cutoff: "BITSAT 290+" },
    ],
    reviews: [
      { author: "Neha Goswami", batch: "2023", rating: 5, text: "Practice School is a complete game-changer. Did PS-II at Google Bangalore and got a PPO. The peer group quality is elite. Curriculum is very industry-aligned.", course: "B.E. CSE" },
      { author: "Rohan Joshi", batch: "2021", rating: 4, text: "Expensive but absolutely worth every rupee. The freedom to choose your courses and dual degree flexibility is unmatched. Campus culture is incredibly entrepreneurial.", course: "B.E. EIE" },
    ],
    tags: ["Private", "BITSAT", "Startup Ecosystem", "Practice School"],
    nirfCategory: "Deemed",
  },
  {
    id: "dtu",
    name: "Delhi Technological University",
    shortName: "DTU",
    location: "New Delhi, Delhi",
    state: "Delhi",
    type: "Government",
    streams: ["Engineering", "Technology", "Management"],
    exams: ["JEE Main"],
    ranking: { nirf: 36, qs: null },
    rating: 4.3,
    totalRating: 1560,
    fees: { min: 80000, max: 120000, annual: 100000 },
    placement: { avg: 1100000, highest: 10000000, rate: 91, median: 800000 },
    campusSize: "164 acres",
    established: 1941,
    accreditation: ["NAAC A+"],
    facilities: ["Central Library", "Sports Ground", "Research Labs", "Hostel", "Central Workshop", "ATM"],
    topRecruiters: ["Amazon", "Paytm", "Oracle", "Adobe", "Samsung", "Phonepe"],
    image: "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=900&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1571260899304-425eee4c7efc?w=800&q=80",
    ],
    description:
      "Delhi Technological University (formerly DCE) is Delhi's premier state engineering institution, with over 80 years of heritage. Known for exceptional value-for-money education, strong industry connections across Delhi-NCR's booming startup and tech scene, and a vibrant campus culture. DTU graduates are highly sought after by Delhi-NCR product companies and MNCs.",
    highlights: ["Delhi's Top State College", "Incredibly Affordable Fees", "91% Placement Rate", "NCR Industry Network"],
    courses: [
      { name: "B.Tech Computer Science & Engineering", duration: "4 years", fees: 100000, seats: 180, cutoff: "97.5 percentile" },
      { name: "B.Tech Software Engineering", duration: "4 years", fees: 100000, seats: 90, cutoff: "97.0 percentile" },
      { name: "B.Tech Information Technology", duration: "4 years", fees: 100000, seats: 90, cutoff: "96.5 percentile" },
      { name: "B.Tech Electronics & Communication", duration: "4 years", fees: 100000, seats: 120, cutoff: "96.0 percentile" },
    ],
    reviews: [
      { author: "Karan Taneja", batch: "2022", rating: 4, text: "Best value college for Delhi students. Ridiculously low fees, great placements, and the location in Delhi is a massive advantage for internships. Startups from Gurugram recruit heavily here.", course: "B.Tech CSE" },
    ],
    tags: ["State College", "Delhi", "Best Value", "NCR Placements"],
    nirfCategory: "State",
  },
  {
    id: "vit-vellore",
    name: "VIT Vellore",
    shortName: "VIT",
    location: "Vellore, Tamil Nadu",
    state: "Tamil Nadu",
    type: "Deemed",
    streams: ["Engineering", "Technology", "Science"],
    exams: ["VITEEE"],
    ranking: { nirf: 11, qs: null },
    rating: 4.2,
    totalRating: 3400,
    fees: { min: 180000, max: 250000, annual: 210000 },
    placement: { avg: 700000, highest: 5000000, rate: 88, median: 600000 },
    campusSize: "370 acres",
    established: 1984,
    accreditation: ["NAAC A++"],
    facilities: ["Smart Classrooms", "Technology Tower", "Gym", "Hostels", "Multiple Cafeterias", "Hospital"],
    topRecruiters: ["TCS", "Cognizant", "Wipro", "Accenture", "Infosys", "Hexaware"],
    image: "https://images.unsplash.com/photo-1519452575417-564c1401ecc0?w=900&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1504275107627-0c2ba7a43dba?w=800&q=80",
    ],
    description:
      "VIT Vellore is one of India's largest private engineering universities with a sprawling 370-acre campus and state-of-the-art infrastructure. Known for high intake, industry partnerships, and international collaborations with 200+ universities worldwide. The FFCS (Fully Flexible Credit System) gives students complete freedom over their academic schedule.",
    highlights: ["NAAC A++ Rating", "370-acre Campus", "200+ Global Tie-ups", "FFCS Flexibility"],
    courses: [
      { name: "B.Tech CSE", duration: "4 years", fees: 210000, seats: 600, cutoff: "VITEEE Rank < 5000" },
      { name: "B.Tech ECE", duration: "4 years", fees: 210000, seats: 400, cutoff: "VITEEE Rank < 10000" },
      { name: "B.Tech Mechanical Engineering", duration: "4 years", fees: 200000, seats: 300, cutoff: "VITEEE Rank < 25000" },
    ],
    reviews: [
      { author: "Pooja Menon", batch: "2023", rating: 4, text: "Massive campus, world-class facilities. International exposure through exchange programs is fantastic. Placement for IT companies is solid. FFCS system is a great concept.", course: "B.Tech CSE" },
    ],
    tags: ["Private", "VITEEE", "International Exchange", "FFCS"],
    nirfCategory: "Deemed",
  },
  {
    id: "iiit-delhi",
    name: "IIIT Delhi",
    shortName: "IIITD",
    location: "New Delhi, Delhi",
    state: "Delhi",
    type: "Government",
    streams: ["Engineering", "Technology"],
    exams: ["JEE Main"],
    ranking: { nirf: 78, qs: null },
    rating: 4.4,
    totalRating: 890,
    fees: { min: 200000, max: 250000, annual: 220000 },
    placement: { avg: 1700000, highest: 18000000, rate: 96, median: 1400000 },
    campusSize: "25 acres",
    established: 2008,
    accreditation: ["NAAC A"],
    facilities: ["State-of-the-art Labs", "Library", "Hostels", "Research Centers", "Maker Space"],
    topRecruiters: ["Google", "Microsoft", "Intuit", "Samsung R&D", "Adobe", "Atlassian"],
    image: "https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=900&q=80",
    gallery: [],
    description:
      "IIIT Delhi is a premier CS-focused institute known for exceptional research output and outstanding placements relative to its age. Despite being only 16 years old, it has built an incredible reputation for producing top-notch software engineers who land offers at Google, Microsoft, and top product companies. The focused curriculum and research-oriented culture attract students who are serious about CS.",
    highlights: ["CS & ECE Focused", "96% Placement Rate", "₹17L Avg Package", "Research-First Culture"],
    courses: [
      { name: "B.Tech CSE", duration: "4 years", fees: 220000, seats: 120, cutoff: "97.0 percentile" },
      { name: "B.Tech CSE + AI", duration: "4 years", fees: 220000, seats: 60, cutoff: "97.5 percentile" },
      { name: "B.Tech ECE", duration: "4 years", fees: 220000, seats: 60, cutoff: "96.0 percentile" },
      { name: "M.Tech CSE", duration: "2 years", fees: 150000, seats: 60, cutoff: "GATE 95 percentile" },
    ],
    reviews: [
      { author: "Aditya Vashistha", batch: "2023", rating: 5, text: "If you are into CS and research, this is the absolute best place. Better placements than most top NITs. Faculty come from CMU, MIT, and top Indian institutions. Very industry-connected.", course: "B.Tech CSE" },
    ],
    tags: ["IIIT", "CS Specialist", "Delhi", "Research Driven"],
    nirfCategory: "IIIT",
  },
  {
    id: "nsut",
    name: "Netaji Subhas University of Technology",
    shortName: "NSUT",
    location: "New Delhi, Delhi",
    state: "Delhi",
    type: "Government",
    streams: ["Engineering", "Technology"],
    exams: ["JEE Main"],
    ranking: { nirf: 68, qs: null },
    rating: 4.1,
    totalRating: 780,
    fees: { min: 70000, max: 110000, annual: 90000 },
    placement: { avg: 950000, highest: 8500000, rate: 88, median: 750000 },
    campusSize: "80 acres",
    established: 1983,
    accreditation: ["NAAC A"],
    facilities: ["Library", "Labs", "Hostel", "Sports Ground", "Cafeteria"],
    topRecruiters: ["Amazon", "Flipkart", "Paytm", "HCL", "TCS", "Capgemini"],
    image: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=900&q=80",
    gallery: [],
    description:
      "NSUT (formerly NSIT) is one of Delhi's top engineering institutes, known for strong placements, affordable fees, and excellent teaching quality. The Dwarka campus offers a modern learning environment. Highly popular among Delhi students who want great placements without the IIT/NIT price tag.",
    highlights: ["Delhi State Top College", "Ultra-Low Fees", "88% Placement Rate", "Strong Alumni in MNCs"],
    courses: [
      { name: "B.Tech Information Technology", duration: "4 years", fees: 90000, seats: 90, cutoff: "96.5 percentile" },
      { name: "B.Tech CSE", duration: "4 years", fees: 90000, seats: 90, cutoff: "96.8 percentile" },
      { name: "B.Tech ECE", duration: "4 years", fees: 90000, seats: 90, cutoff: "95.0 percentile" },
    ],
    reviews: [
      { author: "Sahil Arora", batch: "2022", rating: 4, text: "Incredible value. 90k/year fees with 9-10 LPA placements is unbeatable. Delhi location means easy internships. Community is strong, seniors are very helpful.", course: "B.Tech IT" },
    ],
    tags: ["State College", "Delhi", "Best Value", "Good Placements"],
    nirfCategory: "State",
  },
  {
    id: "manipal",
    name: "Manipal Institute of Technology",
    shortName: "MIT Manipal",
    location: "Manipal, Karnataka",
    state: "Karnataka",
    type: "Deemed",
    streams: ["Engineering", "Technology", "Management"],
    exams: ["MET", "JEE Main"],
    ranking: { nirf: 53, qs: null },
    rating: 4.2,
    totalRating: 2800,
    fees: { min: 280000, max: 380000, annual: 340000 },
    placement: { avg: 850000, highest: 6000000, rate: 87, median: 700000 },
    campusSize: "600 acres",
    established: 1957,
    accreditation: ["NAAC A+"],
    facilities: ["University Town", "Hospital", "Multiple Gyms", "Hostels", "Malls", "Stadium"],
    topRecruiters: ["Infosys", "Wipro", "TCS", "Accenture", "Capgemini", "Bosch"],
    image: "https://images.unsplash.com/photo-1504275107627-0c2ba7a43dba?w=900&q=80",
    gallery: [],
    description:
      "Manipal Institute of Technology, part of the Manipal Academy of Higher Education, is one of India's oldest and most respected private engineering institutions. The Manipal campus is a complete university town with every amenity — from shopping malls and hospitals to stadiums. Known for a diverse student community and very vibrant campus life.",
    highlights: ["60+ Years of Excellence", "Self-Contained University Town", "87% Placement Rate", "International Diversity"],
    courses: [
      { name: "B.Tech CSE", duration: "4 years", fees: 340000, seats: 300, cutoff: "MET / JEE Main" },
      { name: "B.Tech Mechanical", duration: "4 years", fees: 340000, seats: 240, cutoff: "MET / JEE Main" },
      { name: "B.Tech ECE", duration: "4 years", fees: 340000, seats: 240, cutoff: "MET / JEE Main" },
    ],
    reviews: [
      { author: "Rishi Patel", batch: "2022", rating: 4, text: "Manipal is not just a college, it is a life experience. The campus is a city in itself. Social life, cultural diversity, and industry exposure are all top-tier.", course: "B.Tech CSE" },
    ],
    tags: ["Private", "University Town", "International", "Campus Life"],
    nirfCategory: "Deemed",
  },
];

export function getCollegeById(id: string): College | undefined {
  return COLLEGES.find((c) => c.id === id);
}

export function getAllStates(): string[] {
  return [...new Set(COLLEGES.map((c) => c.state))].sort();
}

export function getAllExams(): string[] {
  return [...new Set(COLLEGES.flatMap((c) => c.exams))].sort();
}

export function getAllStreams(): string[] {
  return [...new Set(COLLEGES.flatMap((c) => c.streams))].sort();
}

export const TRENDING_COLLEGES = ["iit-madras", "iit-bombay", "bits-pilani", "iiit-delhi", "nit-trichy"];

export const STATS = {
  colleges: 1247,
  students: 850000,
  reviews: 2400000,
  placements: 97000,
};
